site_name: nf-validation
repo_name: nextflow-io/nf-validation
repo_url: https://github.com/nextflow-io/nf-validation
site_url: https://nextflow-io.github.io/nf-validation/
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Parameters:
      - parameters/index.md
      - parameters/create_schema.md
      - parameters/functions.md
      - parameters/schema_specification.md
  - Sample Sheets:
      - sample_sheets/functions.md
      - sample_sheets/schema_specification.md
      - sample_sheets/immutable_map.md
  - Examples:
      - examples/branch.md
      - examples/count.md
      - examples/multimap.md
  - Contributing:
      - contributing/setup.md

theme:
  name: material
  icon:
    logo: octicons/checklist-16
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.share
    - toc.follow
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - social:
      cards: !ENV [CARDS, true]
